### ISSUE TITLE
JOSS review: main theoretical issue

### ISSUE THREAD

**Issue by vankesteren** [aneeshnaik/lintsampler#8]
Dear authors, 

Hereby an issue to track the main point raised in my review of the work you have submitted to JOSS. See the review thread [here](https://github.com/openjournals/joss-reviews/issues/6906#issuecomment-2181497075). 

First of all, let me congratulate you on the excellent technical state of your package. The documentation, tests, code quality are all top-notch. However, in my opinion an important issue needs to be addressed before the work can be considered for publication in JOSS (note that the editor may disagree!)

The main issue I have is with the statement of need. It is unclear, both in your paper and in your documentation, when I would want / need to use `lintsampler`. 

First, a better description of relevant real-world research situations is needed. It needs to be better than 

> For a small number of well-studied probability distributions, optimised algorithms exist to draw samples cheaply. However, one often wishes to draw samples from an arbitrary PDF for which no such algorithm is available.

As an external reader, I may disagree with the "a small number of well-studied probability distributions", as there is a large number of probability distributions, which cover a wide range of real-world situations from which sampling is relatively easy to do (e.g., your GMM example which is easy to sample from without `lintsampler`). What research problem that you envision does not fall within this set of distributions?

Second, and more pertinent: you do clearly contrast your method to more complex methods such as MCMC, but you fail to compare it to simpler methods like importance sampling. Currently, information is lacking: when is your method preferred over simpler methods? Does it scale well in higher dimensions? Is it computationally more efficient? What is the advantage?

```py
# Example of importance sampling
propdist  = uniform(-12, 24) # or normal(0, 4) or student(2) or ...
proposals = propdist.rvs(1000)
weights   = pdf(proposals) # / propdist.pdf(proposals) not needed because uniform!
samples   = np.random.choice(proposals, 1000, p=weights / weights.sum())
```

In particular, I was curious about whether importance sampling could even be better than `lintsampler` for the same number of samples. The results from my tests — using the examples from your documentation — indeed seem to indicate that importance sampling with a uniform proposal distribution can perform better in those cases. The advantage will only grow with better proposal distributions. The comparison is available in [this GitHub gist](https://gist.github.com/vankesteren/1854cf92b6ec26a3bb9628048bb2b9b6).

**Comment by matt-graham** [comment]
I agree with @vankesteren's comments here and would also like to see the statement of need clarified - I would also echo @vankesteren point that the technical quality of the package here is great, and it might be that the points were are raising here are out of scope for the JOSS review process.

In

> We anticipate `lintsampler` finding use in many applications in scientific research and other areas underpinned by statistics. In such fields, pseudo-random sampling fulfils a myriad of purposes, such as Monte Carlo integration, Bayesian inference, or the generation of initial conditions for numerical simulations. The linear interpolant sampling algorithm underpinning `lintsampler` is a simple and effective alternative to existing techniques, and has no publicly available implementation at present.

you state that pseudo-random sampling can be used for purposes such as Monte Carlo integration or Bayesian inference. To my mind the latter is a specialised subset of the former - the end goal of sampling in Bayesian inference is typically to form Monte Carlo estimates of intractable integrals such as posterior expectations or model evidence terms. In the context of estimating integrals, the linear interpolant sampling algorithm implemented in `lintsampler`, as it relies on some form of tensor product grid on the space being integrated over, I believe will have a computational cost (in terms of the number of evaluations of the integrand / density function)  which scales exponentially in the dimension of the space to achieve a given approximation error. This I think puts linear interpolant sampling in the same computational complexity bracket as numerical quadrature rules for multidimensional integrals based on tensor product grids. Given there are a wide variety of numerical quadrature rules available with well understood numerical convergence properties and a range of Python implementations available, my question would therefore be when / in what sort of problems should a user approximate an integral using linear interpolant sampling rather than a numerical quadrature method?

**Comment by aneeshnaik** [comment]
In response to these comments, we spent some time coming up with a more quantitative treatment of when exactly a user might wish to use `lintsampler` over an alternative technique. To summarise, we came up with 4 'use cases'. The use cases are distinct, but we nonetheless described a 'real world' scenario (drawn from our own research) that encapsulates all of them at once. We've listed these in the paper's Statement of Need, and also added a page to the docs ('When to use `lintsampler`) which contains largely the same content. 

The four use cases are reflected in the four example notebooks in the docs; we've made this explicit in the paper. We've also updated these notebooks to include some code comparisons with alternative techniques. In particular, notebook 1 in the docs now includes a comparison with importance sampling, and notebook 2 now includes comparisons to both importance sampling and MCMC.

You can see all of these changes in the `joss-major` branch of the repo. There is an associated PR (#12) which can be merged into main once you have had a chance to review the changes. To see a built version of the edited docs, you can choose `joss-major` as the 'version' on the readthedocs page (using the interface at the bottom-left corner).

Some more detailed comments responding to some of your points above:
- @vankesteren: in the example you wrote up in your gist, importance sampling outperforms `lintsampler`, but this is because `lintsampler` is being used with a very coarse grid. If you increase the grid resolution, `lintsampler` manages to achieve a comparable log-likelihood to importance sampling. This is actually a point in `lintsampler`'s favour, because you can get there without *too* fine a resolution, and so you can achieve comparable performance to importance sampling with far fewer PDF evaluations. We've written this point up as the first 'use case', and shown this explicitly in the first example notebook.
- @matt-graham: We agree with your assessment that the computational cost scales exponentially with the number of dimensions. We've added a 'caveat' in the Statement of Need indicating that `lintsampler` would rarely be the method of choice for a high-dimensional problem.
